# Correct POST
###
POST http://localhost:8081/location/saveLocation
Content-Type: application/json

{
    "streetAddress": "10 Pleasant Street",
    "city": "Salem",
    "state": "Massachusetts",
    "zipCode": "01941",
   "userId": "65a9605d238e0f4fcf0de0e1"
}

# Incorrect POST
###
POST http://localhost:8081/location/saveLocation
Content-Type: application/json

{
    "streetAddress": "238 Ocean Avenue",
    "city": "Marblehead",
    "state": "Massachusetts",
    "zipCode": "ThisWillFail",
    "userId": "65a9605d238e0f4fcf0de0e1"
}