# Correct POST
###
POST http://localhost:8081/location/saveLocation
Content-Type: application/json

{
    "streetAddress": "2137 Park Drive",
    "city": "Boston",
    "state": "Massachusetts",
    "zipCode": "02108",
    "userId": "65a9605d238e0f4fcf0de0e1",
    "label": "Park Street"
}

# Incorrect POST
###
POST http://localhost:8081/location/saveLocation
Content-Type: application/json

{
    "streetAddress": "238 Ocean Avenue",
    "city": "Marblehead",
    "state": "Massachusetts",
    "zipCode": "ThisWillFail",
    "userId": "65a9605d238e0f4fcf0de0e1"
}