# Correct GET request for getting all routes for a given user
###
GET http://localhost:8081/route/getAllRoutes/65a9605d238e0f4fcf0de0e1 
Content-Type: application/json

# Incorrect GET request -- user does not exist
### 
GET http://localhost:8081/route/getAllRoutes/FakeUser123 
#Content-Type: application/json

# Correct POST request
###
POST http://localhost:8081/route/saveRoute
Content-Type: application/json

{
    "userId": "65a9605d238e0f4fcf0de0e1",
    "start": "65e9251a42a9d721d45e7810",
    "destination": "65e9254842a9d721d45e7812", 
    "stops": ["65e927d007e18b3428c2ef24", "65e929cb07e18b3428c2ef26"],
    "label": "Morning Commute"
}

# Correct edit POST request
###
#PUT http://localhost:8081/route/editRoute/65e941b8372a26bf25732b09
#Content-Type: application/json
#Accept: application/json

#{
#    "start": "65e9251a42a9d721d45e7810",
#    "destination": "65e9254842a9d721d45e7812", 
#    "stops": ["65e927d007e18b3428c2ef24", "65e929cb07e18b3428c2ef26"],
#    "label": "University Commute",
#    "userId": "65a9605d238e0f4fcf0de0e1",
#}

# Get one route by route ID
###
GET http://localhost:8081/route/getRouteById/65e95934f09969c5456e2868
Content-Type: application/json

# Correct POST delete all per 1 user
###
POST http://localhost:8081/route/deleteAllRoutes/65a9605d238e0f4fcf0de0e1

# Incorrect POST delete all per 1 user
###
POST http://localhost:8081/route/deleteAllRoutes/65a9605d238e0f4fcf0de0e7